# -*- coding:UTF-8 -*-
"""User增加新的字段and增加Article

Revision ID: 9a42d2cf84ad
Revises: e759cf4ded3f
Create Date: 2020-04-11 13:38:50.062394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a42d2cf84ad'
down_revision = 'e759cf4ded3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=True),
    sa.Column('head', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column(u'user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'last_seen')
    op.drop_column(u'user', 'about_me')
    op.drop_table('article')
    # ### end Alembic commands ###
